### ISSUE TITLE
Panic when piped into head

### ISSUE THREAD

**Issue by Darksonn** [phsym/prettytable-rs#103]
When the output of the table is piped into `head`, the library panics. The issue was noticed in the [measureme repo](https://github.com/rust-lang/measureme/issues/31).

A minimal example would be

```rust
use prettytable::{Table, row, cell};

fn main() {
    let mut table = Table::new();
    for i in 1..=10 {
        table.add_row(row!["ROW NUMBER", i]);
    }
    table.printstd();
}
```

Run this with `cargo run | head`, and it will produce the output

```
$ RUST_BACKTRACE=1 cargo run | head
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/testtt`
+------------+----+
| ROW NUMBER | 1  |
+------------+----+
| ROW NUMBER | 2  |
+------------+----+
| ROW NUMBER | 3  |
+------------+----+
| ROW NUMBER | 4  |
+------------+----+
| ROW NUMBER | 5  |
thread 'main' panicked at 'Cannot print table to standard output : Broken pipe (os error 32)', /home/alice/.cargo/registry/src/github.com-1ecc6299db9ec823/prettytable-rs-0.8.0/src/lib.rs:194:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: prettytable::TableSlice::print_tty
             at /home/alice/.cargo/registry/src/github.com-1ecc6299db9ec823/prettytable-rs-0.8.0/src/lib.rs:194
   8: prettytable::TableSlice::printstd
             at /home/alice/.cargo/registry/src/github.com-1ecc6299db9ec823/prettytable-rs-0.8.0/src/lib.rs:209
   9: prettytable::Table::printstd
             at /home/alice/.cargo/registry/src/github.com-1ecc6299db9ec823/prettytable-rs-0.8.0/src/lib.rs:376
  10: testtt::main
             at src/main.rs:8
  11: std::rt::lang_start::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by wookietreiber** [comment]
FYI This is reproducible without cargo, i.e. by directly running the compiled program: `target/debug/program | head`.

**Comment by dontlaugh** [comment]
There's a way around this in the library: use the `print` method on a table.

```rs
let mut out = std::io::stdout();
table.print(&mut out);  // ignoring the Result<T, E> here
```
In any case, it would probably be better to avoid panicking on a failed write, as it's not necessarily an error.

**Comment by phsym** [comment]
Hi guys, sorry for the late reply, the past months have been quite busy ones here.

Any comment on the PR ?

**Comment by andjo403** [comment]
@phsym do you think that a new version with this fix will be released soon to crates.io?
